"""
Base agent interface for KineticStack.

Provides abstract base class for all agentic reasoning components.
"""

from abc import ABC, abstractmethod
from typing import Any, Dict


class BaseAgent(ABC):
    """
    Abstract base class for KineticStack agents.

    All agents in the system should inherit from this class and implement
    the reason() and execute() methods.
    """

    def __init__(self, config: Dict[str, Any] = None):
        """
        Initialize the agent.

        Args:
            config: Configuration dictionary for agent-specific settings.
        """
        self.config = config or {}

    @abstractmethod
    def reason(self, inputs: Dict[str, Any]) -> Dict[str, Any]:
        """
        Perform reasoning based on inputs.

        Args:
            inputs: Dictionary of input data for reasoning.

        Returns:
            Dictionary containing reasoning results and decisions.
        """
        pass

    @abstractmethod
    def execute(self, plan: Dict[str, Any]) -> Any:
        """
        Execute a plan generated by reasoning.

        Args:
            plan: Dictionary containing the execution plan.

        Returns:
            Result of execution.
        """
        pass
